### ISSUE TITLE
No such file or directory : `data/smal_samples/dogs_set_torch_1/statistics_modified_v1.json`

### ISSUE THREAD

**Issue by Theo-Cheynel** [runa91/barc_release#2]
Hi, when running the demo command I get the following stack :
```
Traceback (most recent call last):
  File "scripts/visualize.py", line 24, in <module>
    from stacked_hourglass.datasets.imgcrops import ImgCrops
  File "scripts/../src/stacked_hourglass/datasets/imgcrops.py", line 11, in <module>
    from configs.anipose_data_info import COMPLETE_DATA_INFO        
  File "scripts/../src/stacked_hourglass/datasets/../../configs/anipose_data_info.py", line 42, in <module>
    STATISTICS = load_statistics(statistics_path)
  File "scripts/../src/stacked_hourglass/datasets/../../configs/anipose_data_info.py", line 27, in load_statistics
    with open(statistics_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/ps/scratch/nrueegg/new_projects/Animals/data/smal_samples/dogs_set_torch_1/statistics_modified_v1.json'
```

I downloaded the data from the provided link, however there is no smal_sample directory neither in it, nor in the repository's data/ directory. Is this a file that we are supposed to obtain from somewhere else ?

**Comment by runa91** [comment]
it is the same path as in data_info.py, the issue should be resolved by now.
